package com.example.winkit.data

import okhttp3.OkHttpClient
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import retrofit2.http.GET
import retrofit2.http.Query
import com.example.winkit.BuildConfig
import com.google.gson.annotations.SerializedName

// 1. Data class matching your actual "weekly_policies" table schema
data class SupabaseWeeklyPolicy(
    @SerializedName("policy_id") val policy_id: String,
    @SerializedName("created_at") val created_at: String,
    @SerializedName("worker_id") val worker_id: String,
    @SerializedName("week_start_date") val week_start_date: String,
    @SerializedName("week_end_date") val week_end_date: String,
    @SerializedName("premium_paid") val premium_paid: Double?,
    @SerializedName("max_daily_coverage") val max_daily_coverage: Double?,
    @SerializedName("status") val status: String
)
data class SupabaseWorker(
    val worker_id: String,
    val name: String?,
    val trust_score: Int?,
    val status: String?
)

// 2. Earnings & Activity (For the Wallet Screen)
data class SupabaseDailyActivity(
    val log_date: String?,
    val hours_online: Double?,
    val deliveries_completed: Int?,
    val daily_earnings: Double?
)

// 3. Claims History (For Notifications/History Screen)
data class SupabaseClaim(
    val claim_id: String,
    val payout_amt: Double?,
    val status: String?,
    val created_at: String?
)

interface SupabaseApiService {
    
    // 1. Fetch Policy
    @GET("rest/v1/weekly_policies")
    suspend fun getOfferForRider(
        // CHANGED TO REAL WORKER ID
        @Query("worker_id") workerId: String = "eq.ZEP-1001",
        // CHANGED TO UPPERCASE 'ACTIVE'
        @Query("status") status: String = "eq.ACTIVE" 
    ): List<SupabaseWeeklyPolicy>

    // 2. Fetch Worker Profile
    @GET("rest/v1/Workers")
    suspend fun getWorkerProfile(
        @Query("worker_id") workerId: String = "eq.ZEP-1001"
    ): List<SupabaseWorker>

    // 3. Fetch Wallet/Earnings History (Newest first)
    @GET("rest/v1/worker_daily_activity")
    suspend fun getWorkerActivity(
        @Query("worker_id") workerId: String = "eq.ZEP-1001",
        @Query("order") order: String = "log_date.desc" 
    ): List<SupabaseDailyActivity>

    // 4. Fetch Claims/Payouts History (Newest first)
    @GET("rest/v1/claims_and_payouts")
    suspend fun getWorkerClaims(
        @Query("worker_id") workerId: String = "eq.ZEP-1001",
        @Query("order") order: String = "created_at.desc"
    ): List<SupabaseClaim>
}

object NetworkModule {
    
    // We REMOVED the hardcoded strings here!

    // Interceptor to inject the Supabase Auth headers automatically
    private val httpClient = OkHttpClient.Builder().addInterceptor { chain ->
        val request = chain.request().newBuilder()
            // Pulling the key securely from BuildConfig generated by local.properties
            .addHeader("apikey", BuildConfig.SUPABASE_ANON_KEY)
            .addHeader("Authorization", "Bearer ${BuildConfig.SUPABASE_ANON_KEY}")
            .build()
        chain.proceed(request)
    }.build()

    val api: SupabaseApiService by lazy {
        Retrofit.Builder()
            // Pulling the URL securely from BuildConfig
            .baseUrl(BuildConfig.SUPABASE_URL)
            .client(httpClient)
            .addConverterFactory(GsonConverterFactory.create())
            .build()
            .create(SupabaseApiService::class.java)
    }
}
