package com.example.winkit.utils

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

// 🔥 A top-level helper function so you don't have to type "Translator.tr()" everywhere
fun tr(englishText: String): String {
    if (Translator.currentLang == "en") return englishText
    return Translator.dictionary[Translator.currentLang]?.get(englishText) ?: englishText
}

object Translator {
    // This state variable tells Jetpack Compose to instantly redraw the screen when it changes!
    var currentLang by mutableStateOf("en") 

    val dictionary = mapOf(
        "hi" to mapOf(
            "Wallet Balance" to "वॉलेट बैलेंस",
            "Total Earnings" to "कुल कमाई",
            "Total Payouts" to "कुल भुगतान",
            "Stuck in a Hazard?" to "क्या आप खतरे में फंसे हैं?",
            "Report flooded roads or curfew to initiate manual review." to "मैनुअल समीक्षा शुरू करने के लिए जलभराव वाली सड़कों या कर्फ्यू की रिपोर्ट करें।",
            "Report" to "रिपोर्ट करें",
            "Trigger Relocation" to "स्थानांतरण ट्रिगर करें",
            "Language" to "भाषा",
            "Log Out" to "लॉग आउट",
            
            "Your Policy Offer" to "आपका पॉलिसी ऑफर",
            "Based on your risk profile, here is your weekly coverage plan." to "आपके जोखिम प्रोफ़ाइल के आधार पर, यह आपकी साप्ताहिक कवरेज योजना है।",
            "This policy covers income loss only. It does not cover vehicle damage or medical expenses." to "यह पॉलिसी केवल आय के नुकसान को कवर करती है। यह वाहन के नुकसान या चिकित्सा खर्चों को कवर नहीं करती है।",
            "Swipe to Auto-Pay" to "ऑटो-पे के लिए स्वाइप करें",
            "Setting up Auto-Pay..." to "ऑटो-पे सेट किया जा रहा है...",
            "Authorizing with UPI" to "UPI के साथ अधिकृत किया जा रहा है",
            "Auto-Pay Enabled!" to "ऑटो-पे सक्षम किया गया!",
            "Your coverage is now active." to "आपका कवरेज अब सक्रिय है।",
            "Go to Dashboard" to "डैशबोर्ड पर जाएं",
            "ZONE FLOODING DETECTED" to "क्षेत्र में बाढ़ का पता चला",
            "Deliveries paused in Velachery." to "वेलाचेरी में डिलीवरी रोक दी गई है।",
            "RELOCATION OFFER" to "स्थानांतरण प्रस्ताव",
            "₹150 Surge Bonus" to "₹150 सर्ज बोनस",
            "Guaranteed minimum 5 orders" to "न्यूनतम 5 ऑर्डर की गारंटी",
            "Relocate to Adyar Hub" to "अड्यार हब में स्थानांतरित हों",
            "3.2 km away • ~10 mins" to "3.2 किमी दूर • ~10 मिनट",
            "Accept Route & Bonus" to "रूट और बोनस स्वीकार करें",
            "Stay offline in current zone" to "वर्तमान क्षेत्र में ऑफ़लाइन रहें",
            "MAX DAILY COVERAGE" to "अधिकतम दैनिक कवरेज",
            "No active policy found." to "कोई सक्रिय पॉलिसी नहीं मिली।",
            "Policy Details" to "पॉलिसी विवरण",
            "Protection Activated!" to "सुरक्षा सक्रिय हो गई!",
            "Activation failed" to "सक्रियण विफल रहा",
            "Routing to Adyar. ₹150 Bonus Locked!" to "अड्यार की ओर जा रहे हैं। ₹150 बोनस लॉक हो गया!",
            "Error accepting route:" to "रूट स्वीकार करने में त्रुटि:",

            "Terms & Conditions" to "नियम और शर्तें",
            "Coverage" to "कवरेज",
            "Active" to "सक्रिय",
            "Live Risk Telemetry" to "लाइव रिस्क टेलीमेट्री",
            "3D Sync Active" to "3D सिंक सक्रिय",
            "Safe Zone" to "सुरक्षित क्षेत्र",
            "High Risk" to "उच्च जोखिम",
            "Activate Now • ₹49/wk" to "अभी सक्रिय करें • ₹49/सप्ताह",
            "File Manual Claim" to "मैनुअल क्लेम दर्ज करें",
            "Select Hazard Type" to "खतरे का प्रकार चुनें",
            "Description (Optional)" to "विवरण (वैकल्पिक)",
            "E.g., Road blocked near Velachery bridge" to "उदा., वेलाचेरी ब्रिज के पास सड़क बंद",
            "Cancel" to "रद्द करें",
            "Submit Claim" to "क्लेम जमा करें",
            "Terms of Protection" to "सुरक्षा की शर्तें",
            "1. Parametric Triggers" to "1. पैरामीट्रिक ट्रिगर्स",
            "Payouts are triggered automatically when IMD or independent weather APIs confirm conditions exceed the severe threshold in your designated H3 Hexagon." to "जब IMD या मौसम API पुष्टि करते हैं कि स्थिति गंभीर है, तो भुगतान स्वचालित रूप से हो जाता है।",
            "2. Fraud Prevention" to "2. धोखाधड़ी की रोकथाम",
            "Using mock GPS locations, rooted devices, or submitting false manual claims will result in immediate suspension and forfeiture of the premium." to "नकली GPS या झूठे क्लेम से आपका खाता तुरंत निलंबित कर दिया जाएगा।",
            "3. Payout Limits" to "3. भुगतान सीमाएं",
            "Maximum daily coverage is capped at ₹800. This covers lost potential earnings and does not constitute vehicle or medical insurance." to "अधिकतम दैनिक कवरेज ₹800 है। यह वाहन या चिकित्सा बीमा नहीं है।",
            "I Accept" to "मुझे स्वीकार है",
            "Location required for fraud prevention" to "धोखाधड़ी की रोकथाम के लिए लोकेशन आवश्यक है",
            "Live Risk Metrics" to "लाइव रिस्क मेट्रिक्स",
            "Link Your" to "लिंक करें अपना",
            "Delivery Profile" to "डिलीवरी प्रोफाइल",
            "Select your primary platform to sync your active shifts and verify your identity." to "अपनी सक्रिय शिफ्ट को सिंक करने के लिए अपना प्राथमिक प्लेटफ़ॉर्म चुनें।",
            "ID successfully verified with" to "आईडी सफलतापूर्वक सत्यापित: ",
            "backend. Your active shifts will be synced automatically." to " बैकएंड। आपकी शिफ्ट अपने आप सिंक हो जाएंगी।",
            "Verify" to "सत्यापित करें",
            "Continue" to "जारी रखें",
            "Enter your registered number to get started with your active delivery coverage" to "अपनी सक्रिय डिलीवरी कवरेज शुरू करने के लिए अपना पंजीकृत नंबर दर्ज करें",
            "Send OTP" to "OTP भेजें",
            "New here? " to "नए हैं? ",
            "Sign Up" to "साइन अप करें",
            "Terms of Service  •  Privacy Policy" to "सेवा की शर्तें  •  गोपनीयता नीति",
            "Enter 6-digit OTP" to "6-अंकों का OTP दर्ज करें",
            "Edit" to "संपादित करें",
            "Verify & Login" to "सत्यापित करें और लॉगिन करें",
            "Terms & Privacy Policy" to "नियम और गोपनीयता नीति",
            "1. User Agreement" to "1. उपयोगकर्ता समझौता",
            "By logging in, you agree to WinkIT's platform terms, including GPS telemetry tracking for parametric insurance verification." to "लॉग इन करके, आप WinkIT की शर्तों से सहमत हैं।",
            "2. Data Privacy" to "2. डेटा गोपनीयता",
            "We securely store your phone number and location data exclusively for processing automated risk payouts and fraud prevention." to "हम जोखिम भुगतान के लिए आपका डेटा सुरक्षित रूप से सहेजते हैं।",
            "3. Financial Consent" to "3. वित्तीय सहमति",
            "You authorize WinkIT to process premium deductions and route automated claim payouts directly to your linked wallet." to "आप WinkIT को प्रीमियम काटने और भुगतान करने के लिए अधिकृत करते हैं।",
            "I Accept & Continue" to "मैं स्वीकार करता हूँ और आगे बढ़ता हूँ",
            "Rider ID:" to "राइडर आईडी:",
            "Trust Score" to "ट्रस्ट स्कोर",
            "Full Name" to "पूरा नाम",
            "Email Address" to "ईमेल पता",
            "Phone Number (Verified Identity)" to "फ़ोन नंबर (सत्यापित पहचान)",
            "Save Changes" to "बदलाव सेव करें",
            "Name cannot be empty" to "नाम खाली नहीं हो सकता",
            "Invalid email format" to "अमान्य ईमेल प्रारूप",
            "Profile Updated Successfully" to "प्रोफ़ाइल सफलतापूर्वक अपडेट की गई",
            "Update Failed" to "अपडेट विफल रहा",
            "Ledger History" to "लेजर इतिहास",
            "Wallet" to "वॉलेट",
            "Wallet Balance" to "वॉलेट बैलेंस",
            "Insurance Status" to "बीमा की स्थिति",
            "Weekly Premium" to "साप्ताहिक प्रीमियम",
            "Live Claim Automation" to "लाइव क्लेम ऑटोमेशन",
            "Your hazard report is being verified by our team. Payouts process within 24hrs." to "आपके खतरे की रिपोर्ट हमारी टीम द्वारा सत्यापित की जा रही है। भुगतान 24 घंटे के भीतर संसाधित हो जाएगा।"
        ),
        "ta" to mapOf(
            "Wallet Balance" to "வாலட் இருப்பு",
            "Total Earnings" to "மொத்த வருமானம்",
            "Total Payouts" to "மொத்த கொடுப்பனவுகள்",
            "Stuck in a Hazard?" to "ஆபத்தில் சிக்கியுள்ளீர்களா?",
            "Report flooded roads or curfew to initiate manual review." to "கைமுறை மதிப்பாய்வைத் தொடங்க வெள்ளம் சூழ்ந்த சாலைகள் அல்லது ஊரடங்கு உத்தரவைப் புகாரளிக்கவும்.",
            "Report" to "புகாரளி",
            "Trigger Relocation" to "இடமாற்றத்தைத் தூண்டு",
            "Language" to "மொழி",
            "Log Out" to "வெளியேறு",
            "Rider ID:" to "ரைடர் ஐடி:",
            "Trust Score" to "நம்பிக்கை மதிப்பெண்",
            "Full Name" to "முழு பெயர்",
            "Email Address" to "மின்னஞ்சல் முகவரி",
            "Phone Number (Verified Identity)" to "தொலைபேசி எண் (சரிபார்க்கப்பட்ட அடையாளம்)",
            "Save Changes" to "மாற்றங்களைச் சேமி",
            "Name cannot be empty" to "பெயர் காலியாக இருக்கக்கூடாது",
            "Invalid email format" to "தவறான மின்னஞ்சல் வடிவம்",
            "Profile Updated Successfully" to "சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது",
            "Update Failed" to "புதுப்பிப்பு தோல்வியடைந்தது",

            "Your Policy Offer" to "உங்கள் பாலிசி சலுகை",
            "Based on your risk profile, here is your weekly coverage plan." to "உங்கள் அபாய சுயவிவரத்தின் அடிப்படையில், உங்கள் வாராந்திர கவரேஜ் திட்டம் இதோ.",
            "This policy covers income loss only. It does not cover vehicle damage or medical expenses." to "இந்த பாலிசி வருமான இழப்பை மட்டுமே ஈடுசெய்யும். இது வாகன சேதம் அல்லது மருத்துவ செலவுகளை ஈடுசெய்யாது.",
            "Swipe to Auto-Pay" to "ஆட்டோ-பே செய்ய ஸ்வைப் செய்யவும்",
            "Setting up Auto-Pay..." to "ஆட்டோ-பே அமைக்கப்படுகிறது...",
            "Authorizing with UPI" to "UPI மூலம் அங்கீகரிக்கப்படுகிறது",
            "Auto-Pay Enabled!" to "ஆட்டோ-பே இயக்கப்பட்டது!",
            "Your coverage is now active." to "உங்கள் கவரேஜ் இப்போது செயலில் உள்ளது.",
            "Go to Dashboard" to "டாஷ்போர்டுக்குச் செல்லவும்",
            "ZONE FLOODING DETECTED" to "மண்டலத்தில் வெள்ளம் கண்டறியப்பட்டுள்ளது",
            "Deliveries paused in Velachery." to "வேளச்சேரியில் டெலிவரிகள் நிறுத்தப்பட்டுள்ளன.",
            "RELOCATION OFFER" to "இடமாற்ற சலுகை",
            "₹150 Surge Bonus" to "₹150 சர்ஜ் போனஸ்",
            "Guaranteed minimum 5 orders" to "குறைந்தபட்சம் 5 ஆர்டர்கள் உறுதி",
            "Relocate to Adyar Hub" to "அடையாறு ஹப்பிற்கு மாறவும்",
            "3.2 km away • ~10 mins" to "3.2 கிமீ தூரம் • ~10 நிமி",
            "Accept Route & Bonus" to "வழி & போனஸை ஏற்கவும்",
            "Stay offline in current zone" to "தற்போதைய மண்டலத்தில் ஆஃப்லைனில் இருங்கள்",
            "MAX DAILY COVERAGE" to "அதிகபட்ச தினசரி கவரேஜ்",
            "No active policy found." to "செயலில் உள்ள பாலிசி எதுவும் இல்லை.",
            "Policy Details" to "பாலிசி விவரங்கள்",
            "Protection Activated!" to "பாதுகாப்பு இயக்கப்பட்டது!",
            "Activation failed" to "செயலாக்கம் தோல்வியடைந்தது",
            "Routing to Adyar. ₹150 Bonus Locked!" to "அடையாறுக்குச் செல்கிறது. ₹150 போனஸ் லாக் செய்யப்பட்டது!",
            "Error accepting route:" to "வழியை ஏற்பதில் பிழை:",

            "Terms & Conditions" to "விதிமுறைகள் மற்றும் நிபந்தனைகள்",
            "Coverage" to "கவரேஜ்",
            "Active" to "செயலில் உள்ளது",
            "Live Risk Telemetry" to "நேரலை ஆபத்து டெலிமெட்ரி",
            "3D Sync Active" to "3D ஒத்திசைவு",
            "Safe Zone" to "பாதுகாப்பான மண்டலம்",
            "High Risk" to "அதிக ஆபத்து",
            "Activate Now • ₹49/wk" to "இப்போதே தொடங்குங்கள் • ₹49/வாரம்",
            "File Manual Claim" to "கைமுறை உரிமைகோரலை பதிவு செய்க",
            "Select Hazard Type" to "ஆபத்து வகையைத் தேர்ந்தெடுக்கவும்",
            "Description (Optional)" to "விளக்கம் (விருப்பத்திற்குரியது)",
            "E.g., Road blocked near Velachery bridge" to "எ.கா., வேளச்சேரி பாலம் அருகே சாலை மறியல்",
            "Cancel" to "ரத்து செய்",
            "Submit Claim" to "உரிமைகோரலைச் சமர்ப்பிக்கவும்",
            "Terms of Protection" to "பாதுகாப்பு விதிமுறைகள்",
            "1. Parametric Triggers" to "1. பாராமெட்ரிக் தூண்டுதல்கள்",
            "Payouts are triggered automatically when IMD or independent weather APIs confirm conditions exceed the severe threshold in your designated H3 Hexagon." to "உங்கள் H3 ஹெக்ஸகனில் வானிலை கடுமையான வரம்பை தாண்டும்போது தானாகவே பணம் செலுத்தப்படும்.",
            "2. Fraud Prevention" to "2. மோசடி தடுப்பு",
            "Using mock GPS locations, rooted devices, or submitting false manual claims will result in immediate suspension and forfeiture of the premium." to "போலி ஜிபிஎஸ் அல்லது தவறான உரிமைகோரல்கள் கணக்கை முடக்கும்.",
            "3. Payout Limits" to "3. பேஅவுட் வரம்புகள்",
            "Maximum daily coverage is capped at ₹800. This covers lost potential earnings and does not constitute vehicle or medical insurance." to "அதிகபட்ச தினசரி கவரேஜ் ₹800. இது வாகன அல்லது மருத்துவ காப்பீடு அல்ல.",
            "I Accept" to "நான் ஏற்கிறேன்",
            "Location required for fraud prevention" to "மோசடியைத் தடுக்க இருப்பிடம் தேவை",
            "Live Risk Metrics" to "நேரலை ஆபத்து அளவீடுகள்",
            "Link Your" to "இணைக்கவும் உங்கள்",
            "Delivery Profile" to "டெலிவரி சுயவிவரம்",
            "Select your primary platform to sync your active shifts and verify your identity." to "உங்கள் ஷிப்ட்களை ஒத்திசைக்க முதன்மை தளத்தை தேர்ந்தெடுக்கவும்.",
            "ID successfully verified with" to "ஐடி வெற்றிகரமாக சரிபார்க்கப்பட்டது: ",
            "backend. Your active shifts will be synced automatically." to " பின்தளம். உங்கள் ஷிப்ட்கள் தானாக ஒத்திசைக்கப்படும்.",
            "Verify" to "சரிபார்",
            "Continue" to "தொடரவும்",
            "Enter your registered number to get started with your active delivery coverage" to "உங்கள் டெலிவரி கவரேஜைத் தொடங்க பதிவுசெய்யப்பட்ட எண்ணை உள்ளிடவும்",
            "Send OTP" to "OTP ஐ அனுப்பு",
            "New here? " to "புதியவரா? ",
            "Sign Up" to "பதிவு செய்யவும்",
            "Terms of Service  •  Privacy Policy" to "சேவை விதிமுறைகள்  •  தனியுரிமைக் கொள்கை",
            "Enter 6-digit OTP" to "6 இலக்க OTP ஐ உள்ளிடவும்",
            "Edit" to "திருத்து",
            "Verify & Login" to "சரிபார்த்து உள்நுழைக",
            "Terms & Privacy Policy" to "விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கை",
            "1. User Agreement" to "1. பயனர் ஒப்பந்தம்",
            "By logging in, you agree to WinkIT's platform terms, including GPS telemetry tracking for parametric insurance verification." to "உள்நுழைவதன் மூலம், நீங்கள் WinkIT இன் விதிமுறைகளை ஏற்கிறீர்கள்.",
            "2. Data Privacy" to "2. தரவு தனியுரிமை",
            "We securely store your phone number and location data exclusively for processing automated risk payouts and fraud prevention." to "பேஅவுட்டுகளுக்காக உங்கள் தரவை நாங்கள் பாதுகாப்பாகச் சேமிக்கிறோம்.",
            "3. Financial Consent" to "3. நிதி ஒப்புதல்",
            "You authorize WinkIT to process premium deductions and route automated claim payouts directly to your linked wallet." to "கட்டணங்களைக் கழிக்கவும் பேஅவுட் செய்யவும் WinkIT ஐ அங்கீகரிக்கிறீர்கள்.",
            "I Accept & Continue" to "ஏற்றுக்கொண்டு தொடரவும்",
            "Ledger History" to "லெட்ஜர் வரலாறு",
            "Wallet" to "வாலட்",
            "Wallet Balance" to "வாலட் இருப்பு",
            "Insurance Status" to "காப்பீட்டு நிலை",
            "Weekly Premium" to "வாராந்திர பிரீமியம்",
            "Live Claim Automation" to "நேரலை உரிமைகோரல் ஆட்டோமேஷன்",
            "Your hazard report is being verified by our team. Payouts process within 24hrs." to "உங்கள் அபாய அறிக்கை எங்கள் குழுவால் சரிபார்க்கப்படுகிறது. பணம் செலுத்துதல் 24 மணிநேரத்திற்குள் செயல்படுத்தப்படும்."
        ),
        "kn" to mapOf(
            "Wallet Balance" to "ವಾಲೆಟ್ ಬ್ಯಾಲೆನ್ಸ್",
            "Total Earnings" to "ಒಟ್ಟು ಗಳಿಕೆ",
            "Total Payouts" to "ಒಟ್ಟು ಪಾವತಿಗಳು",
            "Stuck in a Hazard?" to "ಅಪಾಯದಲ್ಲಿ ಸಿಲುಕಿದ್ದೀರಾ?",
            "Report flooded roads or curfew to initiate manual review." to "ಮ್ಯಾನುವಲ್ ವಿಮರ್ಶೆಯನ್ನು ಪ್ರಾರಂಭಿಸಲು ಪ್ರವಾಹಕ್ಕೆ ಸಿಲುಕಿದ ರಸ್ತೆಗಳು ಅಥವಾ ಕರ್ಫ್ಯೂ ವರದಿ ಮಾಡಿ.",
            "Report" to "ವರದಿ ಮಾಡಿ",
            "Trigger Relocation" to "ಸ್ಥಳಾಂತರವನ್ನು ಪ್ರಚೋದಿಸಿ",
            "Language" to "ಭಾಷೆ",
            "Log Out" to "ಲಾಗ್ ಔಟ್",
            "Your Policy Offer" to "ನಿಮ್ಮ ಪಾಲಿಸಿ ಆಫರ್",
            "Based on your risk profile, here is your weekly coverage plan." to "ನಿಮ್ಮ ಅಪಾಯದ ಪ್ರೊಫೈಲ್ ಆಧಾರದ ಮೇಲೆ, ನಿಮ್ಮ ಸಾಪ್ತಾಹಿಕ ಕವರೇಜ್ ಯೋಜನೆ ಇಲ್ಲಿದೆ.",
            "This policy covers income loss only. It does not cover vehicle damage or medical expenses." to "ಈ ಪಾಲಿಸಿಯು ಆದಾಯದ ನಷ್ಟವನ್ನು ಮಾತ್ರ ಒಳಗೊಂಡಿರುತ್ತದೆ. ಇದು ವಾಹನ ಹಾನಿ ಅಥವಾ ವೈದ್ಯಕೀಯ ವೆಚ್ಚಗಳನ್ನು ಒಳಗೊಂಡಿರುವುದಿಲ್ಲ.",
            "Swipe to Auto-Pay" to "ಆಟೋ-ಪೇ ಮಾಡಲು ಸ್ವೈಪ್ ಮಾಡಿ",
            "Setting up Auto-Pay..." to "ಆಟೋ-ಪೇ ಹೊಂದಿಸಲಾಗುತ್ತಿದೆ...",
            "Authorizing with UPI" to "UPI ಮೂಲಕ ದೃಢೀಕರಿಸಲಾಗುತ್ತಿದೆ",
            "Auto-Pay Enabled!" to "ಆಟೋ-ಪೇ ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ!",
            "Your coverage is now active." to "ನಿಮ್ಮ ಕವರೇಜ್ ಈಗ ಸಕ್ರಿಯವಾಗಿದೆ.",
            "Go to Dashboard" to "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ",
            "ZONE FLOODING DETECTED" to "ವಲಯದಲ್ಲಿ ಪ್ರವಾಹ ಪತ್ತೆಯಾಗಿದೆ",
            "Deliveries paused in Velachery." to "ವೇಲಾಚೇರಿಯಲ್ಲಿ ಡೆಲಿವರಿಗಳನ್ನು ನಿಲ್ಲಿಸಲಾಗಿದೆ.",
            "RELOCATION OFFER" to "ಸ್ಥಳಾಂತರ ಆಫರ್",
            "₹150 Surge Bonus" to "₹150 ಸರ್ಜ್ ಬೋನಸ್",
            "Guaranteed minimum 5 orders" to "ಕನಿಷ್ಠ 5 ಆರ್ಡರ್‌ಗಳ ಖಾತರಿ",
            "Relocate to Adyar Hub" to "ಅಡ್ಯಾರ್ ಹಬ್‌ಗೆ ಸ್ಥಳಾಂತರಿಸಿ",
            "3.2 km away • ~10 mins" to "3.2 ಕಿಮೀ ದೂರ • ~10 ನಿಮಿಷ",
            "Accept Route & Bonus" to "ಮಾರ್ಗ ಮತ್ತು ಬೋನಸ್ ಸ್ವೀಕರಿಸಿ",
            "Stay offline in current zone" to "ಪ್ರಸ್ತುತ ವಲಯದಲ್ಲಿ ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿರಿ",
            "MAX DAILY COVERAGE" to "ಗರಿಷ್ಠ ದೈನಂದಿನ ಕವರೇಜ್",
            "No active policy found." to "ಯಾವುದೇ ಸಕ್ರಿಯ ಪಾಲಿಸಿ ಕಂಡುಬಂದಿಲ್ಲ.",
            "Policy Details" to "ಪಾಲಿಸಿ ವಿವರಗಳು",
            "Protection Activated!" to "ರಕ್ಷಣೆ ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ!",
            "Activation failed" to "ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ ವಿಫಲವಾಗಿದೆ",
            "Routing to Adyar. ₹150 Bonus Locked!" to "ಅಡ್ಯಾರ್‌ಗೆ ಹೋಗುತ್ತಿದೆ. ₹150 ಬೋನಸ್ ಲಾಕ್ ಆಗಿದೆ!",
            "Error accepting route:" to "ಮಾರ್ಗವನ್ನು ಸ್ವೀಕರಿಸುವಲ್ಲಿ ದೋಷ:",
            "Terms & Conditions" to "ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು",
            "Coverage" to "ಕವರೇಜ್",
            "Active" to "ಸಕ್ರಿಯ",
            "Live Risk Telemetry" to "ಲೈವ್ ರಿಸ್ಕ್ ಟೆಲಿಮೆಟ್ರಿ",
            "3D Sync Active" to "3D ಸಿಂಕ್ ಸಕ್ರಿಯ",
            "Safe Zone" to "ಸುರಕ್ಷಿತ ವಲಯ",
            "High Risk" to "ಹೆಚ್ಚಿನ ಅಪಾಯ",
            "Activate Now • ₹49/wk" to "ಈಗ ಸಕ್ರಿಯಗೊಳಿಸಿ • ₹49/ವಾರ",
            "File Manual Claim" to "ಮ್ಯಾನುವಲ್ ಕ್ಲೈಮ್ ಫೈಲ್ ಮಾಡಿ",
            "Select Hazard Type" to "ಅಪಾಯದ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
            "Description (Optional)" to "ವಿವರಣೆ (ಐಚ್ಛಿಕ)",
            "E.g., Road blocked near Velachery bridge" to "ಉದಾ., ವೇಲಾಚೇರಿ ಸೇತುವೆ ಬಳಿ ರಸ್ತೆ ಬಂದ್",
            "Cancel" to "ರದ್ದುಮಾಡಿ",
            "Submit Claim" to "ಕ್ಲೈಮ್ ಸಲ್ಲಿಸಿ",
            "Terms of Protection" to "ರಕ್ಷಣೆಯ ನಿಯಮಗಳು",
            "1. Parametric Triggers" to "1. ಪ್ಯಾರಾಮೆಟ್ರಿಕ್ ಟ್ರಿಗ್ಗರ್‌ಗಳು",
            "Payouts are triggered automatically when IMD or independent weather APIs confirm conditions exceed the severe threshold in your designated H3 Hexagon." to "ನಿಮ್ಮ H3 ಹೆಕ್ಸಾಗನ್‌ನಲ್ಲಿ ಹವಾಮಾನ ತೀವ್ರ ಮಿತಿಯನ್ನು ಮೀರಿದಾಗ ಪಾವತಿಗಳನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಮಾಡಲಾಗುತ್ತದೆ.",
            "2. Fraud Prevention" to "2. ವಂಚನೆ ತಡೆಗಟ್ಟುವಿಕೆ",
            "Using mock GPS locations, rooted devices, or submitting false manual claims will result in immediate suspension and forfeiture of the premium." to "ನಕಲಿ ಜಿಪಿಎಸ್ ಅಥವಾ ಸುಳ್ಳು ಕ್ಲೈಮ್‌ಗಳು ತಕ್ಷಣದ ಅಮಾನತಿಗೆ ಕಾರಣವಾಗುತ್ತದೆ.",
            "3. Payout Limits" to "3. ಪಾವತಿ ಮಿತಿಗಳು",
            "Maximum daily coverage is capped at ₹800. This covers lost potential earnings and does not constitute vehicle or medical insurance." to "ಗರಿಷ್ಠ ದೈನಂದಿನ ಕವರೇಜ್ ₹800. ಇದು ವಾಹನ ಅಥವಾ ವೈದ್ಯಕೀಯ ವಿಮೆಯಲ್ಲ.",
            "I Accept" to "ನಾನು ಒಪ್ಪುತ್ತೇನೆ",
            "Location required for fraud prevention" to "ವಂಚನೆ ತಡೆಗಟ್ಟಲು ಸ್ಥಳದ ಅಗತ್ಯವಿದೆ",
            "Live Risk Metrics" to "ಲೈವ್ ರಿಸ್ಕ್ ಮೆಟ್ರಿಕ್ಸ್",
            "Link Your" to "ನಿಮ್ಮ ಲಿಂಕ್ ಮಾಡಿ",
            "Delivery Profile" to "ಡೆಲಿವರಿ ಪ್ರೊಫೈಲ್",
            "Select your primary platform to sync your active shifts and verify your identity." to "ನಿಮ್ಮ ಶಿಫ್ಟ್‌ಗಳನ್ನು ಸಿಂಕ್ ಮಾಡಲು ನಿಮ್ಮ ಪ್ರಾಥಮಿಕ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಅನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
            "ID successfully verified with" to "ID ಯಶಸ್ವಿಯಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ: ",
            "backend. Your active shifts will be synced automatically." to " ಬ್ಯಾಕೆಂಡ್. ಶಿಫ್ಟ್‌ಗಳು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸಿಂಕ್ ಆಗುತ್ತವೆ.",
            "Verify" to "ಪರಿಶೀಲಿಸಿ",
            "Continue" to "ಮುಂದುವರಿಸಿ",
            "Enter your registered number to get started with your active delivery coverage" to "ನಿಮ್ಮ ಡೆಲಿವರಿ ಕವರೇಜ್ ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ನೋಂದಾಯಿತ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
            "Send OTP" to "OTP ಕಳುಹಿಸಿ",
            "New here? " to "ಹೊಸಬರೇ? ",
            "Sign Up" to "ಸೈನ್ ಅಪ್ ಮಾಡಿ",
            "Terms of Service  •  Privacy Policy" to "ಸೇವಾ ನಿಯಮಗಳು  •  ಗೌಪ್ಯತಾ ನೀತಿ",
            "Enter 6-digit OTP" to "6-ಅಂಕಿಯ OTP ನಮೂದಿಸಿ",
            "Edit" to "ತಿದ್ದುಪಡಿ ಮಾಡಿ",
            "Verify & Login" to "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಲಾಗಿನ್ ಮಾಡಿ",
            "Terms & Privacy Policy" to "ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತಾ ನೀತಿ",
            "1. User Agreement" to "1. ಬಳಕೆದಾರ ಒಪ್ಪಂದ",
            "By logging in, you agree to WinkIT's platform terms, including GPS telemetry tracking for parametric insurance verification." to "ಲಾಗಿನ್ ಮಾಡುವ ಮೂಲಕ, ನೀವು WinkIT ನ ನಿಯಮಗಳನ್ನು ಒಪ್ಪುತ್ತೀರಿ.",
            "2. Data Privacy" to "2. ಡೇಟಾ ಗೌಪ್ಯತೆ",
            "We securely store your phone number and location data exclusively for processing automated risk payouts and fraud prevention." to "ಪಾವತಿಗಳಿಗಾಗಿ ನಾವು ನಿಮ್ಮ ಡೇಟಾವನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಸಂಗ್ರಹಿಸುತ್ತೇವೆ.",
            "3. Financial Consent" to "3. ಹಣಕಾಸಿನ ಒಪ್ಪಿಗೆ",
            "You authorize WinkIT to process premium deductions and route automated claim payouts directly to your linked wallet." to "ಪ್ರೀಮಿಯಂಗಳನ್ನು ಕಡಿತಗೊಳಿಸಲು ಮತ್ತು ಪಾವತಿಸಲು ನೀವು WinkIT ಅನ್ನು ಅಧಿಕೃತಗೊಳಿಸುತ್ತೀರಿ.",
            "I Accept & Continue" to "ನಾನು ಒಪ್ಪುತ್ತೇನೆ ಮತ್ತು ಮುಂದುವರಿಯುತ್ತೇನೆ",
            "Rider ID:" to "ರೈಡರ್ ಐಡಿ:",
            "Trust Score" to "ಟ್ರಸ್ಟ್ ಸ್ಕೋರ್",
            "Full Name" to "ಪೂರ್ಣ ಹೆಸರು",
            "Email Address" to "ಇಮೇಲ್ ವಿಳಾಸ",
            "Phone Number (Verified Identity)" to "ಫೋನ್ ಸಂಖ್ಯೆ (ಪರಿಶೀಲಿಸಿದ ಗುರುತು)",
            "Save Changes" to "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
            "Name cannot be empty" to "ಹೆಸರು ಖಾಲಿಯಾಗಿರಬಾರದು",
            "Invalid email format" to "ಅಮಾನ್ಯ ಇಮೇಲ್ ಸ್ವರೂಪ",
            "Profile Updated Successfully" to "ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ",
            "Update Failed" to "ನವೀಕರಣ ವಿಫಲವಾಗಿದೆ",
            "Ledger History" to "ಲೆಡ್ಜರ್ ಇತಿಹಾಸ",
            "Wallet" to "ವಾಲೆಟ್",
            "Wallet Balance" to "ವಾಲೆಟ್ ಬ್ಯಾಲೆನ್ಸ್",
            "Insurance Status" to "ವಿಮೆ ಸ್ಥಿತಿ",
            "Weekly Premium" to "ಸಾಪ್ತಾಹಿಕ ಪ್ರೀಮಿಯಂ",
            "Live Claim Automation" to "ಲೈವ್ ಕ್ಲೈಮ್ ಆಟೊಮೇಷನ್",
            "Your hazard report is being verified by our team. Payouts process within 24hrs." to "ನಿಮ್ಮ ಅಪಾಯದ ವರದಿಯನ್ನು ನಮ್ಮ ತಂಡವು ಪರಿಶೀಲಿಸುತ್ತಿದೆ. ಪಾವತಿಗಳು 24 ಗಂಟೆಗಳ ಒಳಗೆ ಪ್ರಕ್ರಿಯೆಯಾಗುತ್ತವೆ."
        )
    )
}
